export interface User {
  id: string;
  email: string;
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  roles?: UserRole[];
}

export interface UserRole {
  id: string;
  userId: string;
  roleId: string;
  role?: Role;
}

export interface Role {
  id: string;
  name: string;
  description?: string;
  permissions: string[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export class UserEntity implements User {
  constructor(
    public id: string,
    public email: string,
    public username: string,
    public password: string,
    public firstName: string,
    public lastName: string,
    public isActive: boolean = true,
    public createdAt: Date = new Date(),
    public updatedAt: Date = new Date(),
    public roles?: UserRole[],
  ) {}

  static create(
    email: string,
    username: string,
    password: string,
    firstName: string,
    lastName: string,
  ): UserEntity {
    return new UserEntity(
      '', // ID will be generated by the database
      email,
      username,
      password,
      firstName,
      lastName,
    );
  }

  updateProfile(firstName: string, lastName: string): void {
    this.firstName = firstName;
    this.lastName = lastName;
    this.updatedAt = new Date();
  }

  deactivate(): void {
    this.isActive = false;
    this.updatedAt = new Date();
  }

  activate(): void {
    this.isActive = true;
    this.updatedAt = new Date();
  }

  hasRole(roleName: string): boolean {
    return this.roles?.some(userRole => userRole.role?.name === roleName) || false;
  }

  hasPermission(permission: string): boolean {
    return this.roles?.some(userRole => 
      userRole.role?.permissions.includes(permission)
    ) || false;
  }

  getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}
