sonar.projectKey=bookly-monorepo
sonar.organization=henderorlando
sonar.host.url=https://sonarcloud.io
sonar.sources=bookly-monorepo/apps,bookly-monorepo/libs
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.tests=bookly-monorepo/apps,bookly-monorepo/libs
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.sourceEncoding=UTF-8
