import { Injectable, Inject } from '@nestjs/common';
import { CommandHandler, ICommandHandler, EventBus } from '@nestjs/cqrs';
import { LoggingService } from '@logging/logging.service';
import { ApprovalFlowRepository } from '../../../domain/repositories/approval-flow.repository';
import { 
  ApprovalFlowEntity, 
  ApprovalLevelEntity, 
  ApprovalRequestEntity, 
  ApprovalActionEntity,
  ApprovalRequestStatus,
  ApprovalActionType
} from '../../../domain/entities/approval-flow.entity';
import {
  CreateApprovalFlowCommand,
  UpdateApprovalFlowCommand,
  CreateApprovalLevelCommand,
  SubmitReservationForApprovalCommand,
  ProcessApprovalRequestCommand,
  CancelReservationCommand,
  ProcessTimeoutCommand,
  SendApprovalReminderCommand
} from '../approval-flow.commands';
import {
  ReservationSubmittedEvent,
  ApprovalRequestCreatedEvent,
  ReservationApprovedEvent,
  ReservationRejectedEvent,
  ReservationCancelledEvent,
  ApprovalRequestTimeoutEvent,
  ApprovalReminderEvent
} from '../../../domain/events/approval-flow.events';
import { LoggingHelper } from '../../../infrastructure/utils/logging.helper';

@Injectable()
@CommandHandler(CreateApprovalFlowCommand)
export class CreateApprovalFlowHandler implements ICommandHandler<CreateApprovalFlowCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: CreateApprovalFlowCommand): Promise<ApprovalFlowEntity> {
    this.loggingService.log('Creating approval flow', 'CreateApprovalFlowHandler', LoggingHelper.logParams({ command }));

    const approvalFlow = new ApprovalFlowEntity(
      '', // ID will be generated by repository
      command.name,
      command.createdBy,
      command.description,
      command.programId,
      command.resourceType,
      command.categoryId,
      command.isDefault,
      command.requiresAllApprovals,
      command.autoApprovalEnabled,
      command.reviewTimeHours,
      command.reminderHours,
      true, // isActive,
      new Date(), // createdAt
      new Date() // updatedAt
    );

    const createdFlow = await this.approvalFlowRepository.createApprovalFlow(approvalFlow);
    
    this.loggingService.log('Approval flow created successfully', 'CreateApprovalFlowHandler', LoggingHelper.logParams({ 
      flowId: createdFlow.id 
    }));

    return createdFlow;
  }
}

@Injectable()
@CommandHandler(UpdateApprovalFlowCommand)
export class UpdateApprovalFlowHandler implements ICommandHandler<UpdateApprovalFlowCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: UpdateApprovalFlowCommand): Promise<ApprovalFlowEntity> {
    this.loggingService.log('Updating approval flow', 'UpdateApprovalFlowHandler', LoggingHelper.logParams({ command }));

    const existingFlow = await this.approvalFlowRepository.findApprovalFlowById(command.id);
    if (!existingFlow) {
      throw new Error(`Approval flow with ID ${command.id} not found`);
    }

    const updatedFlow = await this.approvalFlowRepository.updateApprovalFlow(command.id, {
      name: command.name,
      description: command.description,
      requiresAllApprovals: command.requiresAllApprovals,
      autoApprovalEnabled: command.autoApprovalEnabled,
      reviewTimeHours: command.reviewTimeHours,
      reminderHours: command.reminderHours,
      isActive: command.isActive
    });

    this.loggingService.log('Approval flow updated successfully', 'UpdateApprovalFlowHandler', LoggingHelper.logParams({ 
      flowId: updatedFlow.id 
    }));

    return updatedFlow;
  }
}

@Injectable()
@CommandHandler(CreateApprovalLevelCommand)
export class CreateApprovalLevelHandler implements ICommandHandler<CreateApprovalLevelCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: CreateApprovalLevelCommand): Promise<ApprovalLevelEntity> {
    this.loggingService.log('Creating approval level', 'CreateApprovalLevelHandler', LoggingHelper.logParams({ command }));

    const approvalLevel = new ApprovalLevelEntity(
      '', // ID will be generated by repository
      command.flowId,
      command.level,
      command.name,
      command.description,
      command.approverRoles,
      command.approverUsers,
      command.requiresAll,
      command.timeoutHours
    );

    const createdLevel = await this.approvalFlowRepository.createApprovalLevel(approvalLevel);
    
    this.loggingService.log('Approval level created successfully', 'CreateApprovalLevelHandler', LoggingHelper.logParams({ 
      levelId: createdLevel.id 
    }));

    return createdLevel;
  }
}

@Injectable()
@CommandHandler(SubmitReservationForApprovalCommand)
export class SubmitReservationForApprovalHandler implements ICommandHandler<SubmitReservationForApprovalCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: SubmitReservationForApprovalCommand): Promise<void> {
    this.loggingService.log('Submitting reservation for approval', 'SubmitReservationForApprovalHandler', LoggingHelper.logParams({ command }));

    // Find applicable approval flow
    const approvalFlow = await this.approvalFlowRepository.findDefaultApprovalFlow(
      command.programId,
      command.resourceType,
      command.categoryId
    );

    if (!approvalFlow) {
      this.loggingService.log('No approval flow found, auto-approving reservation', 'SubmitReservationForApprovalHandler', LoggingHelper.logParams({ command }));
      // Auto-approve if no flow is configured
      this.eventBus.publish(new ReservationApprovedEvent(
        command.reservationId,
        '', // No request ID for auto-approval
        'SYSTEM',
        '',
        'Auto-approved - no approval flow configured',
        true
      ));
      return;
    }

    // Emit reservation submitted event
    this.eventBus.publish(new ReservationSubmittedEvent(
      command.reservationId,
      command.userId,
      command.resourceId,
      approvalFlow.id
    ));

    // Check if auto-approval is enabled
    if (approvalFlow.canAutoApprove()) {
      this.loggingService.log('Auto-approving reservation', 'SubmitReservationForApprovalHandler', LoggingHelper.logParams({ command }));
      this.eventBus.publish(new ReservationApprovedEvent(
        command.reservationId,
        '',
        'SYSTEM',
        '',
        'Auto-approved by system',
        true
      ));
      return;
    }

    // Create approval requests for each level
    const levels = await this.approvalFlowRepository.findApprovalLevelsByFlowId(approvalFlow.id);
    const firstLevel = levels.find(level => level.level === 1);

    if (firstLevel) {
      const timeoutAt = firstLevel.timeoutHours 
        ? new Date(Date.now() + firstLevel.timeoutHours * 60 * 60 * 1000)
        : undefined;

      const approvalRequest = new ApprovalRequestEntity(
        '', // ID will be generated by repository
        command.reservationId,
        firstLevel.id,
        ApprovalRequestStatus.PENDING,
        undefined,
        undefined,
        new Date(),
        undefined,
        timeoutAt
      );

      const createdRequest = await this.approvalFlowRepository.createApprovalRequest(approvalRequest);

      // Get all approvers for this level
      const approverIds = firstLevel.getAllApprovers();

      this.eventBus.publish(new ApprovalRequestCreatedEvent(
        createdRequest.id,
        command.reservationId,
        firstLevel.id,
        approverIds,
        timeoutAt
      ));
    }

    this.loggingService.log('Reservation submitted for approval successfully', 'SubmitReservationForApprovalHandler', LoggingHelper.logParams({ command }));
  }
}

@Injectable()
@CommandHandler(ProcessApprovalRequestCommand)
export class ProcessApprovalRequestHandler implements ICommandHandler<ProcessApprovalRequestCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: ProcessApprovalRequestCommand): Promise<void> {
    this.loggingService.log('Processing approval request', 'ProcessApprovalRequestHandler', LoggingHelper.logParams({ command }));

    const request = await this.approvalFlowRepository.findApprovalRequestById(command.requestId);
    if (!request) {
      throw new Error(`Approval request with ID ${command.requestId} not found`);
    }

    if (!request.isPending()) {
      throw new Error(`Approval request ${command.requestId} is not pending`);
    }

    // Create approval action
    const action = new ApprovalActionEntity(
      '', // ID will be generated by repository
      command.requestId,
      command.approverId,
      command.action === 'APPROVE' ? ApprovalActionType.APPROVED : ApprovalActionType.REJECTED,
      command.comments,
      command.ipAddress,
      command.userAgent
    );

    await this.approvalFlowRepository.createApprovalAction(action);

    // Update approval request
    const updatedRequest = command.action === 'APPROVE' 
      ? request.approve(command.approverId, command.comments)
      : request.reject(command.approverId, command.comments);

    await this.approvalFlowRepository.updateApprovalRequest(command.requestId, updatedRequest);

    // Get the approval level and flow
    const level = await this.approvalFlowRepository.findApprovalLevelById(request.levelId);
    if (!level) {
      throw new Error(`Approval level ${request.levelId} not found`);
    }

    const flow = await this.approvalFlowRepository.findApprovalFlowById(level.flowId);
    if (!flow) {
      throw new Error(`Approval flow ${level.flowId} not found`);
    }

    if (command.action === 'APPROVE') {
      // Check if this completes the approval process
      const isComplete = flow.isComplete(level.level);
      
      this.eventBus.publish(new ReservationApprovedEvent(
        request.reservationId,
        command.requestId,
        command.approverId,
        request.levelId,
        command.comments,
        isComplete
      ));

      // If not complete, create next level request
      if (!isComplete) {
        const nextLevel = flow.getNextLevel(level.level);
        if (nextLevel) {
          const timeoutAt = nextLevel.timeoutHours 
            ? new Date(Date.now() + nextLevel.timeoutHours * 60 * 60 * 1000)
            : undefined;

          const nextRequest = new ApprovalRequestEntity(
            '',
            request.reservationId,
            nextLevel.id,
            ApprovalRequestStatus.PENDING,
            undefined,
            undefined,
            new Date(),
            undefined,
            timeoutAt
          );

          const createdNextRequest = await this.approvalFlowRepository.createApprovalRequest(nextRequest);

          this.eventBus.publish(new ApprovalRequestCreatedEvent(
            createdNextRequest.id,
            request.reservationId,
            nextLevel.id,
            nextLevel.getAllApprovers(),
            timeoutAt
          ));
        }
      }
    } else {
      this.eventBus.publish(new ReservationRejectedEvent(
        request.reservationId,
        command.requestId,
        command.approverId,
        request.levelId,
        command.comments
      ));
    }

    this.loggingService.log('Approval request processed successfully', 'ProcessApprovalRequestHandler');
  }
}

@Injectable()
@CommandHandler(CancelReservationCommand)
export class CancelReservationHandler implements ICommandHandler<CancelReservationCommand> {
  constructor(
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: CancelReservationCommand): Promise<void> {
    this.loggingService.log('Cancelling reservation', 'CancelReservationHandler', LoggingHelper.logParams({ command }));

    this.eventBus.publish(new ReservationCancelledEvent(
      command.reservationId,
      command.userId,
      command.reason
    ));

    this.loggingService.log('Reservation cancelled successfully', 'CancelReservationHandler');
  }
}

@Injectable()
@CommandHandler(ProcessTimeoutCommand)
export class ProcessTimeoutHandler implements ICommandHandler<ProcessTimeoutCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: ProcessTimeoutCommand): Promise<void> {
    this.loggingService.log('Processing timeout', 'ProcessTimeoutHandler', LoggingHelper.logParams({ command }));

    const request = await this.approvalFlowRepository.findApprovalRequestById(command.requestId);
    if (!request) {
      throw new Error(`Approval request with ID ${command.requestId} not found`);
    }

    if (!request.isPending() || !request.isExpired()) {
      return; // Nothing to do
    }

    const timeoutRequest = request.timeout();
    await this.approvalFlowRepository.updateApprovalRequest(command.requestId, timeoutRequest);

    this.eventBus.publish(new ApprovalRequestTimeoutEvent(
      command.requestId,
      request.reservationId,
      request.levelId
    ));

    this.loggingService.log('Timeout processed successfully', 'ProcessTimeoutHandler');
  }
}

@Injectable()
@CommandHandler(SendApprovalReminderCommand)
export class SendApprovalReminderHandler implements ICommandHandler<SendApprovalReminderCommand> {
  constructor(
    @Inject('ApprovalFlowRepository') private readonly approvalFlowRepository: ApprovalFlowRepository,
    private readonly eventBus: EventBus,
    private readonly loggingService: LoggingService
  ) {}

  async execute(command: SendApprovalReminderCommand): Promise<void> {
    this.loggingService.log('Sending approval reminder', 'SendApprovalReminderHandler', LoggingHelper.logParams({ command }));

    const request = await this.approvalFlowRepository.findApprovalRequestById(command.requestId);
    if (!request || !request.isPending()) {
      return; // Nothing to do
    }

    const level = await this.approvalFlowRepository.findApprovalLevelById(request.levelId);
    if (!level) {
      return;
    }

    const approverIds = level.getAllApprovers();

    this.eventBus.publish(new ApprovalReminderEvent(
      command.requestId,
      request.reservationId,
      approverIds,
      command.reminderType
    ));

    this.loggingService.log('Approval reminder sent successfully', 'SendApprovalReminderHandler');
  }
}
