import { ApiProperty } from '@nestjs/swagger';
import { BaseEntityDto } from '../common/base-entity.dto';
import { IsString, IsOptional, IsBoolean, IsObject, IsEnum } from 'class-validator';

export enum DocumentFormat {
  PDF = 'PDF',
  DOCX = 'DOCX',
  HTML = 'HTML'
}

export enum DocumentEventType {
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
  REMINDER = 'REMINDER',
  CONFIRMATION = 'CONFIRMATION',
  CANCELLATION = 'CANCELLATION'
}

export class CreateDocumentTemplateDto {
  @ApiProperty({ description: 'Template name', example: 'Approval Letter Template' })
  @IsString()
  name: string;

  @ApiProperty({ description: 'Template description', required: false })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ description: 'Resource type scope', required: false, example: 'ROOM' })
  @IsOptional()
  @IsString()
  resourceType?: string;

  @ApiProperty({ description: 'Category ID scope', required: false })
  @IsOptional()
  @IsString()
  categoryId?: string;

  @ApiProperty({ description: 'Event type', enum: DocumentEventType })
  @IsEnum(DocumentEventType)
  eventType: DocumentEventType;

  @ApiProperty({ description: 'Document format', enum: DocumentFormat })
  @IsEnum(DocumentFormat)
  format: DocumentFormat;

  @ApiProperty({ description: 'Template file path', required: false })
  @IsOptional()
  @IsString()
  templatePath?: string;

  @ApiProperty({ description: 'Template content with variables', required: false })
  @IsOptional()
  @IsString()
  content?: string;

  @ApiProperty({ description: 'Available variables', type: Object })
  @IsObject()
  variables: any;

  @ApiProperty({ description: 'Is default template', default: false })
  @IsOptional()
  @IsBoolean()
  isDefault?: boolean;

  @ApiProperty({ description: 'Can send as attachment', default: true })
  @IsOptional()
  @IsBoolean()
  canSendAsAttachment?: boolean;

  @ApiProperty({ description: 'Can send as link', default: true })
  @IsOptional()
  @IsBoolean()
  canSendAsLink?: boolean;

  @ApiProperty({ description: 'Created by user ID' })
  @IsString()
  createdBy: string;
}

export class UpdateDocumentTemplateDto {
  @ApiProperty({ description: 'Template name', required: false })
  @IsOptional()
  @IsString()
  name?: string;

  @ApiProperty({ description: 'Template description', required: false })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ description: 'Template content with variables', required: false })
  @IsOptional()
  @IsString()
  content?: string;

  @ApiProperty({ description: 'Available variables', type: Object, required: false })
  @IsOptional()
  @IsObject()
  variables?: any;

  @ApiProperty({ description: 'Can send as attachment', required: false })
  @IsOptional()
  @IsBoolean()
  canSendAsAttachment?: boolean;

  @ApiProperty({ description: 'Can send as link', required: false })
  @IsOptional()
  @IsBoolean()
  canSendAsLink?: boolean;

  @ApiProperty({ description: 'Is active', required: false })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;
}

export class DocumentTemplateDto extends BaseEntityDto {
  @ApiProperty({ description: 'Template name' })
  name: string;

  @ApiProperty({ description: 'Template description' })
  description?: string;

  @ApiProperty({ description: 'Resource type scope' })
  resourceType?: string;

  @ApiProperty({ description: 'Category ID scope' })
  categoryId?: string;

  @ApiProperty({ description: 'Event type', enum: DocumentEventType })
  eventType: DocumentEventType;

  @ApiProperty({ description: 'Document format', enum: DocumentFormat })
  format: DocumentFormat;

  @ApiProperty({ description: 'Template file path' })
  templatePath?: string;

  @ApiProperty({ description: 'Template content with variables' })
  content?: string;

  @ApiProperty({ description: 'Available variables', type: Object })
  variables: any;

  @ApiProperty({ description: 'Is default template' })
  isDefault: boolean;

  @ApiProperty({ description: 'Is active' })
  isActive: boolean;

  @ApiProperty({ description: 'Can send as attachment' })
  canSendAsAttachment: boolean;

  @ApiProperty({ description: 'Can send as link' })
  canSendAsLink: boolean;

  @ApiProperty({ description: 'Created by user ID' })
  createdBy: string;
}

export class GenerateDocumentDto {
  @ApiProperty({ description: 'Template ID' })
  @IsString()
  templateId: string;

  @ApiProperty({ description: 'Reservation ID' })
  @IsString()
  reservationId: string;

  @ApiProperty({ description: 'Variable values for template', type: Object })
  @IsObject()
  variables: any;

  @ApiProperty({ description: 'Generated by user ID' })
  @IsString()
  generatedBy: string;
}

export class GeneratedDocumentDto extends BaseEntityDto {
  @ApiProperty({ description: 'Template ID' })
  templateId: string;

  @ApiProperty({ description: 'Reservation ID' })
  reservationId: string;

  @ApiProperty({ description: 'File name' })
  fileName: string;

  @ApiProperty({ description: 'File path' })
  filePath: string;

  @ApiProperty({ description: 'File size in bytes' })
  fileSize?: number;

  @ApiProperty({ description: 'MIME type' })
  mimeType: string;

  @ApiProperty({ description: 'Variables used for generation', type: Object })
  variables: any;

  @ApiProperty({ description: 'Generated by user ID' })
  generatedBy: string;
}
